const CATEGORY = require('./constant').CATEGORY;

module.exports = [
  CATEGORY.PEOPLE,
  CATEGORY.NATURE,
  CATEGORY.ACTIVITY,
  CATEGORY.PLACES,
  CATEGORY.OBJECTS,
  CATEGORY.SYMBOLS,
  CATEGORY.FLAGS
];
