import { CATEGORY } from './constant';

export default [
  CATEGORY.PEOPLE,
  CATEGORY.NATURE,
  CATEGORY.ACTIVITY,
  CATEGORY.PLACES,
  CATEGORY.OBJECTS,
  CATEGORY.SYMBOLS,
  CATEGORY.FLAGS,
  CATEGORY.OTHER
];
